/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i climate_data_interface.h -p :climate_data_interface.cpp ../HomeScreenAutomotive/Dbus/climate_data.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "climate_data_interface.h"
/*
 * Implementation of interface class LocalClimateInterface
 */
LocalClimateInterface::LocalClimateInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

LocalClimateInterface::~LocalClimateInterface()
{
}

