/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a climate_data_adaptor.h: ../Similator_Source/climate_data.xml
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef CLIMATE_DATA_ADAPTOR_H
#define CLIMATE_DATA_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface local.Climate
 */
class ClimateAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "local.Climate")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"local.Climate\">\n"
"    <signal name=\"dataChanged\"/>\n"
"    <method name=\"getAuto_mode\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"    </method>\n"
"    <method name=\"getDriverWind_mode\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"    </method>\n"
"    <method name=\"getFan_speed\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"    </method>\n"
"    <method name=\"getPassengerWind_mode\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"    </method>\n"
"    <method name=\"getSync_mode\">\n"
"      <arg direction=\"out\" type=\"i\"/>\n"
"    </method>\n"
"    <method name=\"getTemp_driver\">\n"
"      <arg direction=\"out\" type=\"d\"/>\n"
"    </method>\n"
"    <method name=\"getTemp_passenger\">\n"
"      <arg direction=\"out\" type=\"d\"/>\n"
"    </method>\n"
"    <method name=\"setData\">\n"
"      <arg direction=\"in\" type=\"d\" name=\"temp_driver\"/>\n"
"      <arg direction=\"in\" type=\"d\" name=\"temp_passenger\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"fan_speed\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"driver_wind_mode\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"passenger_wind_mode\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"auto_mode\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"sync_mode\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ClimateAdaptor(QObject *parent);
    virtual ~ClimateAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    int getAuto_mode();
    int getDriverWind_mode();
    int getFan_speed();
    int getPassengerWind_mode();
    int getSync_mode();
    double getTemp_driver();
    double getTemp_passenger();
    void setData(double temp_driver, double temp_passenger, int fan_speed, int driver_wind_mode, int passenger_wind_mode, int auto_mode, int sync_mode);
Q_SIGNALS: // SIGNALS
    void dataChanged();
};

#endif
